import './globals.css'
import type { Metadata } from 'next'
import { geist, spaceGrotesk } from '@assets/fonts'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="es">
			<body
				className={`${geist.variable} ${spaceGrotesk.variable} font-geist bg-background text-foreground-light w-full text-base antialiased`}
			>
				{children}
			</body>
		</html>
	)
}
